workflows:
  bootstrap-hypervisor:
    description: Bootstrap selected environment's hypervisor layer
    steps:
      - name: stack_selection
        type: choose
        prompt: "Which stask should be bootstrapped?"
        options: [dev, prod]
        default: !env ATMOS_STACK dev
      # - command: terraform deploy -auto-approve -s {{ .steps.stack_selection.value }} --query '.locals.layer == "hypervisor"'
      - command: terraform deploy -auto-approve -s {{ .steps.stack_selection.value }} --labels layer=hypervisor
        when: always

  teardown-hypervisor:
    description: Destroy selected environment's hypervisor layer
    steps:
      - name: stack_selection
        type: choose
        prompt: "Which stask should be bootstrapped?"
        options: [dev, prod]
        default: !env ATMOS_STACK dev
      # - command: terraform destroy -auto-approve -s {{ .steps.stack_selection.value }} --query '.locals.layer == "hypervisor"'
      - command: terraform destroy -auto-approve -s {{ .steps.stack_selection.value }} --labels layer=hypervisor
