workflows:
  bootstrap-hypervisor:
    description: Bootstrap selected environment's hypervisor layer
    steps:
      - name: stack_selection
        type: choose
        prompt: "Which stask should be bootstrapped?"
        options: [dev, prod]
        default: !env ATMOS_STACK dev
      - command: terraform apply -auto-approve -s {{ .steps.stack_selection.value }} proxmox/snippet/cloudinit_vendor_data
      - command: terraform apply -auto-approve -s {{ .steps.stack_selection.value }} proxmox/disk_image/ubuntu_noble
      - command: terraform apply -auto-approve -s {{ .steps.stack_selection.value }} proxmox/vm/template/ubuntu_noble
      - command: terraform apply -auto-approve -s {{ .steps.stack_selection.value }} proxmox/vm/template/nixos
        when: always

  teardown-hypervisor:
    description: Destroy selected environment's hypervisor layer
    steps:
      - name: stack_selection
        type: choose
        prompt: "Which stask should be bootstrapped?"
        options: [dev, prod]
        default: !env ATMOS_STACK dev
      - command: terraform destroy -auto-approve -s {{ .steps.stack_selection.value }} proxmox/vm/template/nixos
      - command: terraform destroy -auto-approve -s {{ .steps.stack_selection.value }} proxmox/vm/template/ubuntu_noble
      - command: terraform destroy -auto-approve -s {{ .steps.stack_selection.value }} proxmox/disk_image/ubuntu_noble
      - command: terraform destroy -auto-approve -s {{ .steps.stack_selection.value }} proxmox/snippet/cloudinit_vendor_data
