x-linuxserver-env: &linuxserver-env
  PUID: ${UID}
  PGID: ${GID}
  TZ: ${TZ}

include:
  - ./coredns/compose.yml
  - ./lldap/compose.yml
  - ./authelia/compose.yml
  - ./caddy/compose.yml
  - ./dashy/compose.yml
  - ./hedgedoc/compose.yml
  - ./transmission/compose.yml
  - ./arr/compose.yml
  - ./jellyfin/compose.yml
  - ./samba/compose.yml
