x-linuxserver-env: &linuxserver-env
  PUID: 1000
  PGID: 1000
  TZ: Europe/Madrid

x-route-through-vpn: &route-through-vpn
  network_mode: service:wireguard
  depends_on:
    - wireguard

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/wireguard:/config
    ports:
      - 51820:51820/udp
      # Transmission webUI
      - 9091:9091
    restart: unless-stopped

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/nginx-proxy-manager/data:/data
      - ${CONFIG_VOLUMES_PATH}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 81:81
      - 443:443
    restart: unless-stopped


  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/transmission:/config
      - ${DATA_VOLUMES_PATH}/torrents:/data/torrents
    <<: *route-through-vpn
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/sonarr:/config
      - ${DATA_VOLUMES_PATH}:/data
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/jellyfin:/config
      - ${DATA_VOLUMES_PATH}/media:/data/media
    restart: unless-stopped

  dashy:
    image: lissy93/dashy
    container_name: dashy
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/dashy:/app/user-data
    restart: unless-stopped
    