services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${CONFIG_VOLUMES_PATH}/wireguard/config:/config
    ports:
      - 51820:51820/udp
      # Transmission webUI
      - 9091:9091
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${CONFIG_VOLUMES_PATH}/transmission/config:/config
      - ${DATA_VOLUMES_PATH}/downloads:/downloads
    network_mode: service:wireguard
    depends_on:
      - wireguard
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_VOLUMES_PATH}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_VOLUMES_PATH}/sonarr/config:/config
      # TODO: get rid of these if possible
      - ${DATA_VOLUMES_PATH}/tv:/tv #optional
      - ${DATA_VOLUMES_PATH}/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
