x-linuxserver-env: &linuxserver-env
  PUID: 1000
  PGID: 1000
  TZ: Europe/Madrid

x-route-through-vpn: &route-through-vpn
  network_mode: service:wireguard
  depends_on:
    - wireguard

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/wireguard:/config
    ports:
      - 51820:51820/udp
      # Transmission webUI
      - 9091:9091
    restart: unless-stopped

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/nginx-proxy-manager/data:/data
      - ${CONFIG_VOLUMES_PATH}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ./authelia/snippets:/snippets
    ports:
      - 80:80
      - 81:81
      - 443:443
    restart: unless-stopped


  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/transmission:/config
      - ${DATA_VOLUMES_PATH}/torrents:/data/torrents
    <<: *route-through-vpn
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/sonarr:/config
      - ${DATA_VOLUMES_PATH}:/data
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/jellyfin:/config
      - ${DATA_VOLUMES_PATH}/media:/data/media
    restart: unless-stopped

  dashy:
    image: lissy93/dashy
    container_name: dashy
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/dashy:/app/user-data
    restart: unless-stopped

  authelia:
    image: authelia/authelia
    container_name: authelia
    secrets: [
      RESET_PASSWORD_JWT_SECRET,
      LDAP_PASSWORD,
      SESSION_SECRET,
      STORAGE_ENCRYPTION_KEY,
      OIDC_HMAC_SECRET,
      OIDC_JWKS_PRIVATE_KEY,
      OIDC_JELLYFIN_CLIENT_ID,
      OIDC_JELLYFIN_CLIENT_SECRET
    ]
    environment:
      <<: *linuxserver-env
      BASE_DOMAIN: docker.services.buen.ga
      X_AUTHELIA_CONFIG: /config/config_files
      X_AUTHELIA_CONFIG_FILTERS: template
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/RESET_PASSWORD_JWT_SECRET
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: dc=buen,dc=ga
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: uid=authelia,ou=people,dc=buen,dc=ga
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE:  /run/secrets/LDAP_PASSWORD
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /run/secrets/OIDC_HMAC_SECRET
    volumes:
      - ${CONFIG_VOLUMES_PATH}/authelia:/config
      - ./authelia/config:/config/config_files
    restart: unless-stopped

  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    environment:
      UID: 1000
      GID: 1000
      TZ: Europe/Madrid
    volumes:
      - ${CONFIG_VOLUMES_PATH}/lldap:/data
    restart: unless-stopped

secrets:
  RESET_PASSWORD_JWT_SECRET:
    file: ./authelia/secrets/RESET_PASSWORD_JWT_SECRET
  LDAP_PASSWORD:
    file: ./authelia/secrets/LDAP_PASSWORD
  SESSION_SECRET:
    file: ./authelia/secrets/SESSION_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ./authelia/secrets/STORAGE_ENCRYPTION_KEY
  OIDC_HMAC_SECRET:
    file: ./authelia/secrets/OIDC_HMAC_SECRET
  OIDC_JWKS_PRIVATE_KEY:
    file: ./authelia/secrets/OIDC_JWKS_PRIVATE_KEY
  OIDC_JELLYFIN_CLIENT_ID:
    file: ./authelia/secrets/OIDC_JELLYFIN_CLIENT_ID
  OIDC_JELLYFIN_CLIENT_SECRET:
    file: ./authelia/secrets/OIDC_JELLYFIN_CLIENT_SECRET
