import:
  - catalog/vm/defaults
  - catalog/k3s/defaults

components:
  terraform:
    mirror-devpod:
      metadata:
        inherits:
          - vm/defaults
      vars:
        config:
          name: mirror-devpod
          os_preset: devpod
          hardware_preset: xxl
          advanced:
            proxmox:
              allowed_nodes: [devimon]
    arch:
      metadata:
        inherits:
          - vm/defaults
      vars:
        config:
          name: arch
          hardware_preset: md
          advanced:
            proxmox:
              vm_template_id: 1000
    k3s-cluster:
      metadata:
        inherits:
          - k3s/defaults
      vars:
        config:
          name: cluster
