import:
  - catalog/vm/defaults
  - catalog/k3s/defaults

components:
  terraform:
    mirror-devpod:
      metadata:
        inherits:
          - vm/defaults
      vars:
        config:
          name: mirror-devpod
          os_preset: devpod
          hardware_preset: xxl
          advanced:
            proxmox:
              allowed_nodes: [devimon]

    arch:
      metadata:
        inherits:
          - vm/defaults
      vars:
        config:
          name: arch
          hardware_preset: md
          advanced:
            proxmox:
              vm_template_id: 1000

    k3s-cluster:
      metadata:
        inherits:
          - k3s/defaults
      vars:
        config:
          name: cluster

    cloudinit-vendor-data:
      metadata:
        component: proxmox/snippet
      vars:
        config:
          name: cloudinit-vendor-data.yaml
          data: !include.raw ../config/cloudinit-vendor-data.yaml

    ubuntu-24-iso:
      metadata:
        component: proxmox/disk_image
      vars:
        config:
          name: ubuntu-24-noble-server-cloudimg-amd64.qcow2
          url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

    ubuntu-24-template:
      metadata:
        component: proxmox/vm
      vars:
        proxmox:
          default_cloudinit_vendor_data_file_id: !terraform.state cloudinit-vendor-data id
        config:
          name: ubuntu-24-template
          image_id: !terraform.state ubuntu-24-iso id
          hardware_preset: md
          advanced:
            template: true

    ubuntu-24-vm:
      metadata:
        component: proxmox/vm
      vars:
        config:
          name: ubuntu-24
          template_id: !terraform.state ubuntu-24-template id
          hardware_preset: md
          user:
            name: buengabacho
            ssh_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBGuvLnYXThp0dvDp/W7mZOnnpE9i+NClbYJwx5hsHIU # Bitwarden SSH key

    ubuntu-24-static-ip-vm:
      metadata:
        component: proxmox/vm
      vars:
        config:
          name: ubuntu-24-static-ip
          template_id: !terraform.state ubuntu-template id
          hardware_preset: md
          user:
            name: buengabacho
            ssh_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBGuvLnYXThp0dvDp/W7mZOnnpE9i+NClbYJwx5hsHIU # Bitwarden SSH key
          advanced:
            ip_config:
              ipv4:
                address: 192.168.140.20/24
                gateway: 192.168.140.1
