import:
  - catalog/proxmox/vm/template
  - catalog/proxmox/vm/nixos

components:
  terraform:
    proxmox/snippet/cloudinit_vendor_data:
      metadata:
        component: proxmox/snippet
      vars:
        proxmox:
          node: !env PM_DEFAULT_NODE
          iso_storage: !env PM_DEFAULT_ISO_STORAGE
        config:
          name: cloudinit_vendor_data.yaml
          data: !include.raw config/cloudinit_vendor_data.yaml

    proxmox/disk_image/ubuntu_noble:
      metadata:
        component: proxmox/disk_image
      vars:
        proxmox:
          node: !env PM_DEFAULT_NODE
          iso_storage: !env PM_DEFAULT_ISO_STORAGE
        config:
          name: ubuntu-24-noble-server-cloudimg-amd64.qcow2
          url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

    proxmox/vm/template/ubuntu_noble:
      metadata:
        component: proxmox/vm
        inherits:
          - proxmox/vm/template
      vars:
        config:
          name: template-ubuntu-noble
          disk_image_id: !terraform.state proxmox/disk_image/ubuntu_noble id
          advanced:
            cloud_init:
              vendor_data_file_id: !terraform.state proxmox/snippet/cloudinit_vendor_data id
      dependencies:
        components:
          - name: proxmox/disk_image/ubuntu_noble
          - name: proxmox/snippet/cloudinit_vendor_data

    proxmox/vm/nixos/template_placeholder:
      metadata:
        component: proxmox/nixos_vm
        inherits:
          - proxmox/vm/nixos
      vars:
        config:
          name: nixos-placeholder
          vm_id: !env PM_PLACEHOLDER_VM_ID
          clone_id: !terraform.output proxmox/vm/template/ubuntu_noble id
          advanced:
            ip_config:
              ipv4:
                address: !env PM_PLACEHOLDER_VM_STATIC_IP_ADDRESS
                gateway: !env PM_PLACEHOLDER_VM_GATEWAY
        nixos_config:
          flake_path: !exec echo "$(git rev-parse --show-toplevel)/infra/nixos"
          preset: cloudinit
      dependencies:
        components:
          - name: proxmox/vm/template/ubuntu_noble

    proxmox/vm/template/nixos:
      metadata:
        component: proxmox/vm
        inherits:
          - proxmox/vm/template
      vars:
        config:
          name: template-nixos
          clone_id: !env PM_PLACEHOLDER_VM_ID
          advanced:
            ip_config:
              ipv4:
                address: dhcp
      hooks:
        prepare_placeholder_vm:
          events: [before.terraform.plan, before.terraform.apply]
          kind: steps
          with:
            - type: atmos
              command: "terraform apply -auto-approve -s {{ .stack }} proxmox/vm/nixos/template_placeholder"
            - type: shell
              command: 'curl --insecure -X POST -H "Authorization: PVEAPIToken=$PM_API_TOKEN" $PM_API_URL/api2/json/nodes/$PM_DEFAULT_NODE/qemu/$PM_PLACEHOLDER_VM_ID/status/stop'
          on_failure: fail
        cleanup_placeholder_vm:
          events: [after.terraform.apply]
          when: always
          kind: step
          type: atmos
          with:
            command: "terraform destroy -auto-approve -s {{ .stack }} proxmox/vm/nixos/template_placeholder"
          on_failure: fail
      dependencies:
        components:
          - name: proxmox/vm/nixos/template_placeholder
