import:
  - catalog/proxmox/vm/defaults
  - catalog/proxmox/vm/template

components:
  terraform:
    proxmox/snippet/cloudinit_vendor_data:
      metadata:
        component: proxmox/snippet
        labels:
          layer: hypervisor
      vars:
        proxmox:
          node: !env PM_DEFAULT_NODE
          iso_storage: !env PM_DEFAULT_ISO_STORAGE
        config:
          name: cloudinit_vendor_data.yaml
          data: !include.raw config/cloudinit_vendor_data.yaml

    proxmox/disk_image/ubuntu_noble:
      metadata:
        component: proxmox/disk_image
        labels:
          layer: hypervisor
      vars:
        proxmox:
          node: !env PM_DEFAULT_NODE
          iso_storage: !env PM_DEFAULT_ISO_STORAGE
        config:
          name: ubuntu-24-noble-server-cloudimg-amd64.qcow2
          url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

    proxmox/vm/template/ubuntu_noble:
      metadata:
        component: proxmox/vm
        inherits:
          - proxmox/vm/template
        labels:
          layer: hypervisor
      vars:
        config:
          name: template-ubuntu-noble
          disk_image_id: !terraform.state proxmox/disk_image/ubuntu_noble id
          advanced:
            cloud_init:
              vendor_data_file_id: !terraform.state proxmox/snippet/cloudinit_vendor_data id
      dependencies:
        components:
          - name: proxmox/disk_image/ubuntu_noble
          - name: proxmox/snippet/cloudinit_vendor_data

    proxmox/vm/template/nixos:
      metadata:
        component: proxmox/nixos_vm
        inherits:
          - proxmox/vm/defaults
        labels:
          layer: hypervisor
      locals:
        base_api_command: 'curl --insecure -H "Authorization: PVEAPIToken=$PM_API_TOKEN" $PM_API_URL/api2/json/nodes'
      vars:
        config:
          name: template-nixos
          clone_id: !terraform.state proxmox/vm/template/ubuntu_noble id
          advanced:
            ip_config:
              ipv4:
                address: !env PM_PLACEHOLDER_VM_STATIC_IP_ADDRESS
                gateway: !env PM_PLACEHOLDER_VM_GATEWAY
        nixos_config:
          flake_path: '{{ atmos.Resolve "!git.root" }}/infra/nixos'
          preset: cloudinit
      hooks:
        convert_to_template:
          events: [after.terraform.apply]
          kind: steps
          with:
            - name: vm_node
              type: atmos
              command: "terraform output -s {{ .atmos_stack }} --skip-init {{ .atmos_component }} -raw node"
            - name: vm_id
              type: atmos
              command: "terraform output -s {{ .atmos_stack }} --skip-init {{ .atmos_component }} -raw id"
            - type: shell
              command: '{{ .locals.base_api_command }}/{{ atmos.Resolve "{{ .steps.vm_node.value }}/qemu/{{ .steps.vm_id.value }}/agent/shutdown" }} -X POST'
            - type: shell
              command: '{{ .locals.base_api_command }}/{{ atmos.Resolve "{{ .steps.vm_node.value }}/qemu/{{ .steps.vm_id.value }}/config" }} -X POST --data template=1 --data-urlencode ipconfig0="ip=dhcp"'
          on_failure: fail
      dependencies:
        components:
          - name: proxmox/vm/template/ubuntu_noble
