import:
  - catalog/vm/default

components:
  terraform:
    vm/ubuntu/noble:
      metadata:
        type: abstract
        inherits:
          - vm/default
      vars:
        config:
          clone_id: !terraform.state ubuntu-noble-template id
      dependencies:
        components:
          - name: ubuntu-noble-template
