vars:
  stage: controlplane

import:
  - deploy/_defaults
  - catalog/vm/md

components:
  terraform:
    devpod:
      metadata:
        inherits:
          - vm/md
      vars:
        vm_name: devpod