vars:
  stage: controlplane

import:
  - deploy/_defaults
  - catalog/vm/md
  - catalog/vm/xl

components:
  terraform:
    devpod:
      metadata:
        inherits:
          - vm/xl
      vars:
        config:
          name: devpod
          os_preset: devpod
          advanced:
            proxmox:
              vm_vlan_tag: 120
