vars:
  stage: controlplane

import:
  - deploy/_defaults
  - catalog/vm/md

components:
  terraform:
    devpod:
      metadata:
        inherits:
          - vm/md
      vars:
        vm_name: devpod
        nixos_flake:
          path: !exec echo "$(git rev-parse --show-toplevel)/infra/nixos"
          configuration_name: devpod
