import:
  - deploy/_defaults
  - layers/bootstrap
  - layers/compute
  - mixins/stage/prod

components:
  terraform:
    mirror-devpod:
      vars:
        config:
          user:
            name: rodrizapico
            ssh_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKe/HIxUFzDHiwSK4fefAX/4qwz+yZtmjPCeSUMpYcy0 # 1Password SSH key
