vars:
  stage: prod

import:
  - deploy/_defaults
  - catalog/vm/xxl

components:
  terraform:
    mirrorDevpod:
      metadata:
        inherits:
          - vm/xxl
      vars:
        vm_name: mirrorDevpod
        vlan_tag: 120
        nixos_flake:
          configuration_name: devpod
        nixos_user:
          name: rodrizapico
          ssh_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKe/HIxUFzDHiwSK4fefAX/4qwz+yZtmjPCeSUMpYcy0 # 1Password SSH key
