import:
  - catalog/vm/xl

components:
  terraform:
    vm/2xl:
      metadata:
        type: abstract
        inherits:
          - vm/xl
      vars:
        config:
          hardware_preset: custom
          advanced:
            hardware:
              core_count: 4
              memory_capacity: 16384
              storage_capacity: 250G
