components:
  terraform:
    vm/defaults:
      metadata:
        component: vm
        type: abstract
      vars:
        config:
          proxmox:
            host: agumon
            template: nixos-cloudinit-template
          hardware:
            core_count: 2
            memory_capacity: 2048
            storage:
              location: ceph_data
              capacity: 50G
            networking:
              bridge: vmbr0
              vlan_tag: 140
          settings:
            autostart: true
            startup_shutdown_order: -1
            user:
              name: buengabacho
              ssh_keys:
                - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBGuvLnYXThp0dvDp/W7mZOnnpE9i+NClbYJwx5hsHIU # Bitwarden SSH key
          nixos:
            flake:
              path: !exec echo "$(git rev-parse --show-toplevel)/infra/nixos"
