import:
  - catalog/vm/defaults

components:
  terraform:
    vm/lg:
      metadata:
        type: abstract
        inherits:
          - vm/defaults
      vars:
        config:
          hardware_preset: lg
