import:
  - catalog/vm/defaults

components:
  terraform:
    vm/sm:
      metadata:
        type: abstract
        inherits:
          - vm/defaults
      vars:
        config:
          hardware_preset: sm
