import:
  - catalog/vm/defaults

components:
  terraform:
    vm/xl:
      metadata:
        type: abstract
        inherits:
          - vm/defaults
      vars:
        config:
          proxmox:
            host: devimon
          hardware:
            core_count: 2
            memory_capacity: 8192
            storage:
              capacity: 100G
