import:
  - catalog/vm/defaults

components:
  terraform:
    vm/xl:
      metadata:
        type: abstract
        inherits:
          - vm/defaults
      vars:
        config:
          hardware:
            core_count: 2
            memory_capacity: 8192
            storage_capacity: 100G
          advanced:
            proxmox:
              allowed_nodes: [devimon]
