import:
  - catalog/vm/defaults

components:
  terraform:
    vm/xl:
      metadata:
        type: abstract
        inherits:
          - vm/defaults
      vars:
        config:
          hardware_preset: xl
          advanced:
            proxmox:
              allowed_nodes: [devimon]
