import:
  - catalog/vm/xl

components:
  terraform:
    vm/xxl:
      metadata:
        type: abstract
        inherits:
          - vm/xl
      vars:
        config:
          hardware:
            core_count: 4
            memory_capacity: 16384
            storage_capacity: 250G
