---
###############################################################################
##                        Storage Provider Configuration                     ##
###############################################################################

storage:
  #
  # Postgres
  #
  postgres:
    address: "tcp://authelia_db:5432"
    database: "authelia"
    username: "postgres"
