x-linuxserver-env: &linuxserver-env
  PUID: ${UID}
  PGID: ${GID}
  TZ: ${TZ}

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/sonarr:/config
      - ${DATA_VOLUMES_PATH}:/data
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      <<: *linuxserver-env
    volumes:
      - ${CONFIG_VOLUMES_PATH}/bazarr:/config
      - ${DATA_VOLUMES_PATH}/media:/data/media
    restart: unless-stopped
