---
###############################################################################
##                Authentication Backend Provider Configuration              ##
###############################################################################

authentication_backend:
  # Password Reset Options.
  password_reset:
    # Disable both the HTML element and the API for reset password functionality.
    disable: false

  # The amount of time to wait before we refresh data from the authentication backend in the duration common syntax.
  # To disable this feature set it to 'disable', this will slightly reduce security because for Authelia, users will
  # always belong to groups they belonged to at the time of login even if they have been removed from them in LDAP.
  # To force update on every request you can set this to '0' or 'always', this will increase processor demand.
  # See the below documentation for more information.
  # Refresh Interval docs: https://www.authelia.com/c/1fa#refresh-interval
  refresh_interval: 5m

  #
  # LDAP (Authentication Provider)
  #
  # This is the recommended Authentication Provider in production
  # because it allows Authelia to offload the stateful operations
  # onto the LDAP service.
  ldap:
    # The address of the directory server to connect to in the address common syntax.
    # Format: [<scheme>://]<hostname>[:<port>].
    # Square brackets indicate optional portions of the format. Scheme must be 'ldap', 'ldaps', or 'ldapi`.
    # The default scheme is 'ldapi' if the address is an absolute path otherwise it's 'ldaps'.
    # The default port is '636', unless the scheme is 'ldap' in which case it's '389'.
    address: "ldap://lldap:3890"

    # The LDAP implementation, this affects elements like the attribute utilised for resetting a password.
    # Acceptable options are as follows:
    # - 'activedirectory' - for Microsoft Active Directory.
    # - 'freeipa' - for FreeIPA.
    # - 'lldap' - for lldap.
    # - 'custom' - for custom specifications of attributes and filters.
    # This currently defaults to 'custom' to maintain existing behaviour.

    # Depending on the option here certain other values in this section have a default value, notably all of the
    # attribute mappings have a default value that this config overrides, you can read more about these default values
    # at https://www.authelia.com/c/ldap#defaults
    implementation: "lldap"

    # The dial timeout for LDAP in the duration common syntax.
    timeout: "5 seconds"

    ## The users filter used in search queries to find the user profile based on input filled in login form.
    ## Various placeholders are available in the user filter which you can read about in the documentation which can
    ## be found at: https://www.authelia.com/c/ldap#users-filter-replacements
    ##
    ## Recommended settings are as follows:
    ## - Microsoft Active Directory: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
    ## - OpenLDAP:
    ##   - (&({username_attribute}={input})(objectClass=person))
    ##   - (&({username_attribute}={input})(objectClass=inetOrgPerson))
    ##
    ## To allow sign in both with username and email, one can use a filter like
    ## (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    # users_filter: '(&({username_attribute}={input})(objectClass=person))'

    ## The groups filter used in search queries to find the groups based on relevant authenticated user.
    ## Various placeholders are available in the groups filter which you can read about in the documentation which can
    ## be found at: https://www.authelia.com/c/ldap#groups-filter-replacements
    ##
    ## If your groups use the `groupOfUniqueNames` structure use this instead:
    ##    (&(uniqueMember={dn})(objectClass=groupOfUniqueNames))
    # groups_filter: '(&(member={dn})(objectClass=groupOfNames))'

    ## The group search mode to use. Options are 'filter' or 'memberof'. It's essential to read the docs if you wish to
    ## use 'memberof'. Also 'filter' is the best choice for most use cases.
    # group_search_mode: 'filter'
