components:
  terraform:
    proxmox/vm/defaults:
      metadata:
        component: proxmox/vm
        type: abstract
      vars:
        config:
          node: !env PM_DEFAULT_NODE
          instance_type: md
          user:
            generate_ssh_keys: true
          advanced:
            hardware:
              bridge: !env PM_DEFAULT_VM_BRIDGE
              vlan_tag: !env PM_DEFAULT_VM_VLAN_TAG
              storage:
                location: !env PM_DEFAULT_VM_STORAGE
